FROM windowsservercore

ENV GOLANG_VERSION 1.6.1
ENV GOLANG_DOWNLOAD_URL "https://golang.org/dl/go$GOLANG_VERSION.windows-amd64.zip"

RUN powershell -Command \
	(New-Object System.Net.WebClient).DownloadFile('%GOLANG_DOWNLOAD_URL%', 'go.zip') ; \
	Expand-Archive go.zip -DestinationPath c:\\ ; \
	Remove-Item go.zip -Force

RUN setx /M PATH "C:\go\bin;%PATH%" && \
	setx /M GOPATH "C:\go"
